package org.laukvik.sql;


import org.laukvik.csv.CSV;
import org.laukvik.csv.CsvReader;
import org.laukvik.csv.ParseException;
import org.laukvik.csv.Row;
import org.laukvik.sql.ddl.*;

import java.io.*;
import java.nio.charset.Charset;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Logger;

/**
 * Created by morten on 14.10.2015.
 */
public class Importer {

    private final static Logger LOG = Logger.getLogger(Importer.class.getName());
    private DatabaseConnection db;

    public Importer(DatabaseConnection databaseConnection) {
        this.db = databaseConnection;
    }

    /*
    public void importDatabase(File file){
        LOG.info("Importing database to file: " + file.getAbsolutePath() );
        System.out.println("Importing database to file: " + file.getAbsolutePath() );
        StringBuilder b = new StringBuilder();
        byte [] buffer = new byte[2048];
        try(FileInputStream in = new FileInputStream( file )) {
            in.read(buffer);
            b.append(buffer);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    */

    /**
     * Reads Table definition persisted in a file
     *
     * @param table
     * @param file
     * @return
     * @throws ParseException
     * @throws IOException
     */
    public static Table readTableMetadata(String table, File file) throws ParseException, IOException {
        Table t = new Table( table );
        CSV csv = new CSV( file );
        for (int y=0; y<csv.getRowCount(); y++){
            //
            Row r = csv.getRow(y);
            //
            Column c =Column.parse( r.getInteger("type"), r.getString("column"));
            //Column c = new IntegerColumn( r.getString("column") );
            c.setAllowNulls( r.getBoolean("allowNulls") );
            c.setPrimaryKey( r.getBoolean("primaryKey") );
            c.setForeignKey(  ForeignKey.parse(r.getString("foreignKey")));
            c.setAutoIncrement( r.getBoolean("autoIncrement") );
            c.setAutoGenerated(r.getBoolean("autoGenerated"));
            c.setComments(r.getString("comments"));
            c.setDefaultValue(r.getString("default"));
            t.addColumn(c);
        }
        return t;
    }

    /**
     * Imports the specified table into the database. Both a metadata file and
     * the data file must be found in order to import.
     *
     * @param directory
     * @param tableName
     * @throws Exception
     */
    public long importCSV( File directory, String tableName ) throws Exception {
        if (!directory.isDirectory()){
            return -1;
        }
        //
        File meta = new File( directory.getPath(), tableName + ".meta.csv");
        Table t = Importer.readTableMetadata(tableName,meta);
        createTable(t);

        File data = new File( directory.getPath(), tableName + ".csv");
        InputStream is = new FileInputStream(data);

        CsvReader r = new CsvReader( is );
        System.out.println( r.getMetaData().getColumn(0).getName() );
        long updateCount = 0;
        long failedCount = 0;
        try(
                Connection conn = db.getConnection();
                Statement st = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet rs = st.executeQuery("SELECT * FROM " + tableName );
        ){
            int n = 1;
            while(r.hasNext()){

                Row row = r.getRow();
                try{
                    // Prepare new row
                    rs.moveToInsertRow();

                    // Fill data
                    for (int x=0; x<t.getColumns().size(); x++){
                        // Get column definition
                        Column c = t.getColumns().get(x);
                        int columnIndex = x+1;
                        //if (c.isAutoGenerated() || c.isAutoIncrement()){
                             // Don't do anything with generated values
                        //} else {
                            //
                            if (c instanceof IntegerColumn){
                                Integer value = row.getInteger(x);
                                rs.updateInt(columnIndex, value );

                            } else if (c instanceof VarCharColumn){
                                String value = row.getString(x);
                                rs.updateString(columnIndex, value);
                            }
                        //}
                    }

                    // Add new row
                    rs.insertRow();
                    updateCount++;
                    LOG.info("Row #" + n + " imported." );
                } catch(SQLException e2){
                    failedCount++;
                    LOG.info("Row #" + n + " - " + e2.getMessage() );
                }
                n++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        LOG.info("Imported " + updateCount + " rows. " + failedCount + " rows failed!" );
        return updateCount;
    }

    /**
     *
     * @param table
     */
    private void createTable( Table table ){
        try(
                Connection conn = db.getConnection();
                Statement st = conn.createStatement();
        ){
            int results = st.executeUpdate(table.getDDL());
            LOG.info("Created table " + table + " with " + table.getColumns().size() + " columns.");
        } catch (Exception e) {
            LOG.info("Failed to create table " + table +"! (" + e.getMessage() + ")" );
        }
    }



}
