package org.laukvik.sql;

import com.sun.tools.internal.ws.wsdl.document.Import;
import org.laukvik.csv.CSV;
import org.laukvik.csv.CsvReader;
import org.laukvik.csv.ParseException;
import org.laukvik.csv.Row;
import org.laukvik.sql.ddl.Column;
import org.laukvik.sql.ddl.ForeignKey;
import org.laukvik.sql.ddl.IntegerColumn;
import org.laukvik.sql.ddl.Table;

import java.io.*;
import java.nio.charset.Charset;
import java.util.logging.Logger;

/**
 * Created by morten on 14.10.2015.
 */
public class Importer {

    private final static Logger LOG = Logger.getLogger(Importer.class.getName());
    private DatabaseConnection db;

    public Importer(DatabaseConnection databaseConnection) {
        this.db = databaseConnection;
    }

    public void importDatabase(File file){
        LOG.info("Importing database to file: " + file.getAbsolutePath() );
        System.out.println("Importing database to file: " + file.getAbsolutePath() );
        StringBuilder b = new StringBuilder();
        byte [] buffer = new byte[2048];
        try(FileInputStream in = new FileInputStream( file )) {
            in.read(buffer);
            b.append(buffer);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static Table readTableMetadata(String table, File file) throws ParseException, IOException {
        Table t = new Table( table );
        CSV csv = new CSV( file );
        for (int y=0; y<csv.getRowCount(); y++){
            //
            Row r = csv.getRow(y);
            //
            Column c = new IntegerColumn( r.getString("column") );
            c.setAllowNulls( r.getBoolean("allowNulls") );
            c.setPrimaryKey( r.getBoolean("primaryKey") );
            c.setForeignKey(  ForeignKey.parse(r.getString("foreignKey")));
            c.setAutoIncrement( r.getBoolean("autoIncrement") );
            c.setAutoGenerated(r.getBoolean("autoGenerated"));
            c.setComments(r.getString("comments"));
            c.setDefaultValue(r.getString("default"));
            t.addColumn(c);
        }
        return t;
    }

    /**
     *
     *
     *
     * @throws Exception
     */
    public void importCSV( File directory, String tableName ) throws Exception {
        if (!directory.isDirectory()){
            return;
        }
        //
        File meta = new File( directory.getPath(), tableName + ".meta.csv");
        Table t = Importer.readTableMetadata(tableName,meta);
        createTable(t);

        File data = new File( directory.getPath(), tableName + ".csv");
        InputStream is = new FileInputStream(data);

        CsvReader r = new CsvReader( is );
        System.out.println( r.getMetaData().getColumn(0).getName() );
        int x = 1;
        while(r.hasNext()){
            Row row = r.getRow();
            insertRow(row, x);
            x++;
        }
    }

    private void createTable( Table table ){
        System.out.println( table.getDDL() );
    }

    private void insertRow( Row row, int x ){
        System.out.println( "Importing #" + (x) + ": " + row.getString(0) );
    }

}
